pipeline {
        agent any
        stages {
          stage('Cloning from GitHub') {
            steps {
                git branch: 'develop', credentialsId: 'github-private-key', url: 'https://github.com/khaoulaBouslimi/Summer-Internship-2022'
                }
                
                }
                
         
          stage("build & SonarQube analysis") {
            steps {
                      withSonarQubeEnv('SonarQube') {
                        bat 'mvn clean package sonar:sonar'
                      }
                    }
                  }

          stage("Quality Gate") {
                    steps {
                    timeout(time: 1, unit: 'HOURS') {
                        waitForQualityGate abortPipeline: true
                    }
                    }
                    }
         
         



        
        }

}
        
