pipeline {
        agent any
        stages {
          stage("hello world !") {
                                    steps {
                                            echo'hello world !'
                                    }
                                }
                
          stage("Build") {
                            steps {
                                    echo'Building !'
                            }
                        }
                
          stage("Test") {
                            steps {
                                    echo'Testing !'
                            }
                        }      
        }
        
        
}
