pipeline {
        agent any
        stages {
          stage('Cloning from GitHub') {
                steps {
                    git branch: 'develop', credentialsId: 'github-private-key', url: 'https://github.com/khaoulaBouslimi/Summer-Internship-2022'
                }
                
            }


            
                
         stage('Code Analysis with SONARQUBE') {
                environment{
                    scannerHome = tool 'SonarQube'

                }
                steps{
                    
                    withSonarQubeEnv(credentialsId: 'joujou2',installationName: 'SonarQube') {
                        withCredentials([string(credentialsId: 'khaoula', variable: '707a76f307c14ed1b1844a78534345d0')]) {
                            sh '''
                                mvn sonar:sonar \
                                -D sonar.projectKey=org.springframework.boot \
                                -D sonar.host.url=http://102.159.202.139:9000 \
                                -D sonar.login=admin \
                                -D sonar.password=-469GxqQSz7.fs. \
                                -D sonar.projectBaseDir=C:/ProgramData/Jenkins/.jenkins/workspace/summerInternship2 
                                '''

                        } 
                        
                    }

                }
            }    
         



        
        }

}
        
